apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal-service
  name: drupal-service
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30095
  selector:
    app: drupal-frontend
  type: "NodePort"
